---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:bionic

    steps:
      - run: pwd; ls -al; id -a
      - run: apt update &&
          apt install -y
          zip grep file ca-certificates autotools-dev autoconf automake
          git bc wget rsync cmake make pkg-config yasm libtool
          libv4l-dev ssh gzip tar
          libmagickwand-dev libmagickwand-6-headers
          imagemagick autoconf gettext
          build-essential libv4l-dev coreutils

      - checkout
      - run: ls -al; pwd

      - run: mkdir -p ~/work/deploy
      - run: autoreconf -v --install -f
      - run: ./configure --without-python --without-gtk --without-qt --without-java --without-x --with-gtk=no --with-x=no
      - run: make -j $(nproc) check
      - run: file ./zbarcam/.libs/zbarcam
      - run: ls -hal ./zbarcam/.libs/zbarcam
      - run: ls -al ./zbarcam/.libs/zbarcam
      - run: export LD_LIBRARY_PATH=./zbar/.libs/ ; ldd ./zbarcam/.libs/zbarcam
      - run: export LD_LIBRARY_PATH=./zbar/.libs/ ; ./zbarcam/.libs/zbarcam --help

      #- store_artifacts:
      #    path: ~/work/deploy
      #    destination: deploy


